sudo: false

language: c

addons:
  apt:
    packages:
    # GHC
    - libgmp-dev
    # Selenium
    - xvfb

cache:
  directories:
    - $HOME/.stack
    - .stack-work

matrix:
  include:
    - env: ARGS=""
    - env: ARGS="--resolver nightly"

  allow_failures:
    - env: ARGS="--resolver nightly"

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

before_script:
- sh -e /etc/init.d/xvfb start
- export DISPLAY=:99.0
- travis_retry wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
- java -jar selenium-server-standalone-2.53.1.jar 2> /dev/null &
- sleep 5

script:
 - stack $ARGS --no-terminal --install-ghc build --test

before_cache:
# This directory changes after every build. If we cache it, the cache
# would have to be reuploaded after every build.
- rm -rf .stack-work/downloaded
